# Generated by Django 2.2.16 on 2021-12-04 06:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.TextField(default=uuid.uuid4, editable=False, max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
