# Generated by Django 2.2.16 on 2021-12-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20211211_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, related_name='titles', to='reviews.Category', verbose_name='Категория'),
        ),
    ]
