# Generated by Django 2.2.16 on 2021-12-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20211205_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=254, unique=True, verbose_name='Адрес электронной почты'),
        ),
    ]
